# Generated by Django 5.1.2 on 2025-04-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatus',
            old_name='expert_id',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='serviceprioritydmform',
            old_name='expert',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='servicevideoform',
            old_name='expert',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='servicewebinarform',
            old_name='expert',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_expert',
            new_name='is_creator',
        ),
    ]
