# Generated by Django 5.1.2 on 2025-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expertuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
