# Generated by Django 5.1.2 on 2025-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevideoform',
            name='selectedDates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicevideoform',
            name='selectedTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
