# Generated by Django 5.1.2 on 2025-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expertuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='aboutyourself',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
