# Generated by Django 5.1.2 on 2025-02-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_expertuser_aboutyourself_expertuser_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='alternateContactNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='alternateEmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='officeAddress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='personalAddress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
