# Generated by Django 5.1.2 on 2025-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_servicevideoform_selecteddates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevideoform',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
