# Generated by Django 5.1.2 on 2025-02-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_expertuser_alternatecontactnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertuser',
            old_name='username',
            new_name='userName',
        ),
    ]
