# Generated by Django 5.1.2 on 2025-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_servicevideoform_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlugRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
    ]
