# Generated by Django 5.1.2 on 2025-02-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_username_expertuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertuser',
            old_name='userName',
            new_name='User_name',
        ),
    ]
