# Generated by Django 5.1.2 on 2025-04-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_serviceslugrouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprioritydmform',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicewebinarform',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
