# Generated by Django 5.1.2 on 2025-02-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_username_expertuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertuser',
            name='User_name',
        ),
    ]
