# Generated by Django 5.1.2 on 2025-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_serviceprioritydmform_slug_servicewebinarform_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='session_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
