# Generated by Django 5.1.2 on 2025-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_expertuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
