# Generated by Django 5.1.2 on 2025-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_servicevideoform_buffertime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='additionalDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
