# Generated by Django 5.1.2 on 2025-04-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_bookingstatus_additionaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevideoform',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
