# Generated by Django 5.1.2 on 2025-03-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_serviceform_servicewebinarform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprioritydmform',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='servicevideoform',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='servicewebinarform',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
