# Generated by Django 5.1.2 on 2025-03-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_serviceprioritydmform_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
