# Generated by Django 5.1.2 on 2025-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevideoform',
            name='maxBookings',
        ),
        migrations.RemoveField(
            model_name='servicevideoform',
            name='selectedDates',
        ),
        migrations.RemoveField(
            model_name='servicevideoform',
            name='selectedTime',
        ),
        migrations.RemoveField(
            model_name='servicevideoform',
            name='timezone',
        ),
        migrations.AddField(
            model_name='availability',
            name='maxBookings',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
