# Generated by Django 5.1.2 on 2025-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_servicevideoform_maxbookings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='maxBookings',
        ),
        migrations.AddField(
            model_name='servicevideoform',
            name='maxBookings',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
