# Generated by Django 5.1.2 on 2025-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_expertuser_is_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertuser',
            name='instagramlink',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='youtubelink',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
