# Generated by Django 5.1.2 on 2025-04-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_availability_maxbookings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatus',
            name='booking_timezone',
        ),
    ]
