# Generated by Django 5.1.2 on 2025-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_expertuser_instagramlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(blank=True, max_length=100, null=True)),
                ('session_name', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(blank=True, max_length=7, null=True)),
                ('user_id', models.IntegerField(blank=True, max_length=100, null=True)),
                ('expert_id', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
