# Generated by Django 5.1.2 on 2025-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='selectedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='selectedTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
